# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go get github.com/getlantern/systray@v1.2.2
          go get github.com/skratchdot/open-golang@v0.0.0-20200116055534-eef842397966
          go get github.com/getlantern/golog@v0.0.0-20190830074920-4ef2e798c2d7
          go get github.com/getlantern/hidden@v0.0.0-20190325191715-f02dbb02be55
          go get github.com/getlantern/errors@v0.0.0-20190325191628-abdb3e3e36f7
          go get github.com/getlantern/ops@v0.0.0-20190325191751-d70cb0d6f85f
          go get github.com/oxtoacart/bpool@v0.0.0-20190530202638-03653db5a59c
          go get github.com/getlantern/hex@v0.0.0-20190417191902-c6586a6fe0b7
          go get github.com/getlantern/context@v0.0.0-20190109183933-c447772a6520
          go get github.com/go-stack/stack@v1.8.0
          sudo apt-get install -y libayatana-appindicator3-dev

      - name: Build
        run: |
          go build -o mackernews.app -ldflags="-s -w \
            -X 'main.icon=<icon-file-location>' \
            -X 'main.BundleID=<bundle-identifier>' \
            -X 'main.Version=<version>'" .
